### PR TITLE
Install gitpod for auto-built previews on each PR

### PR DESCRIPTION
**Pull request by jywarren**

### CODE REVIEW

**Comment by jywarren** [comment]
Hmm. I can't seem to figure out how to get the GitPod button/bot to appear?

**Comment by jywarren** [comment]
Ref https://github.com/publiclab/image-sequencer/pull/1668

**Comment by nisarhassan12** [comment]
@jywarren Maybe try merging this PR and the gitpod bot will hopefully appear. Let me know it does not.

**Comment by jywarren** [comment]
Hi @nisarhassan12 - so sorry to bother you again, but it looks like it didn't start working. Do you work with GitPod? I feel bad annoying you with these issues, it's just a bit mysterious to me. Thanks for your help!

**Comment by nisarhassan12** [comment]
Hey! Thanks, I work for them. Feel free to hit me up at any time. I'm sorry that I'm a bit un-responsive. 

Also if you were to report here https://community.gitpod.io/ if you are having some issues and so on. we are more responsive on discourse.

Regarding the issue. I'm not sure what's wrong. 

@jankeromnes Can you have a look at this? Thanks

**Comment by jywarren** [comment]
Thank you @nisarhassan12 -- no, you're very responsive and super helpful, thank you!!

I will report there too. Many thanks!

**Comment by jywarren** [comment]
Great, posted here! https://community.gitpod.io/t/cant-get-github-bot-to-appear-despite-app-install-and-config-file/1594

**Comment by jywarren** [comment]
Working again, here is an example! Thanks! https://github.com/jywarren/woofmark/pull/28

**Pull request merged**
