### PR TITLE
Replacing uglify-js with Terser

### PR DESCRIPTION
**Pull request by cypherean**
* Replaces uglify-js with terser
* Updates `jshint`, `clean-css`, `stylus`
* fixes errors with tests and warnings
* updates `dist/` folder

### CODE REVIEW

**Comment by cypherean** [comment]
Please review @jywarren @sagarpreet-chadha @keshav234156 @NitinBhasneria @Shulammite-Aso

**Comment by jywarren** [comment]
Hi! Do we run grunt build in .travis.yml? That way we see a Travis failure if the build script fails? 

Thank you!!

**Comment by cypherean** [comment]
Right now we use `npm` as a build tool. Should I add grunt as a dev dependency and configure a gruntfile or making tweaks to travis.yml can tell us if a build has failed with npm?

**Comment by jywarren** [comment]
Oh sorry, npm! Thanks!

**Comment by cypherean** [comment]
Is this okay @jywarren?
Screenshot from 2020-07-25 18-22-58

**Review by sagarpreet-chadha — APPROVED** [review]
Wowow 💯 
Terser supports ES6 also, right?

**Comment by jywarren** [comment]
Perfect. Let's do it!

**Pull request merged**
