### PR TITLE
Adding Jest tests

### PR DESCRIPTION
**Pull request by jywarren**
Moving from https://github.com/jywarren/woofmark/pull/7 !

### CODE REVIEW

**Comment by jywarren** [comment]
Hmm. I think then this may need to be rebased? @Shulammite-Aso i'm so sorry but this should go relatively smoothly after we fix this. Thanks for your hard work and I LOVE the Jest tests!!!

**Comment by Shulammite-Aso** [comment]
> Hmm. I think then this may need to be rebased?

Oh, has conflicts. I should probably just open another PR🤔 I can't rebase this one I think? because I didn't open it,  is it?

**Comment by jywarren** [comment]
Ah that's fine as well, thank you! Good point. :-)

**Comment by Shulammite-Aso** [comment]
i think you should close this one @jywarren ?  so i can create the new one.

**Comment by jywarren** [comment]
Ah ok, i'll do that. Thanks!

**Pull request closed without merging**
