### PR TITLE
Latest changes of bevacque

### PR DESCRIPTION
**Pull request by NitinBhasneria**
This PR is for making the `jywarren/woofmark` branch `plots2` up to date with `bevacque/woofmark` branch `master`.

### CODE REVIEW

**Comment by NitinBhasneria** [comment]
@jywarren here it is.
Well, I cant see the `resolve conflicts` option may be due to rights issues.

**Comment by jywarren** [comment]
Ah, well, i think it's because it can't figure out how to auto-resolve them. I guess perhaps we should've done this first, but it's OK -- we can do 2 things -- try to simply rebase this over our plots2 branch, OR try to rebase the plots2 branch over this. I think without too many changes yet it's not going to be /too/ hard either way, but would you like to give one of the two a try? 

Thank you, Nitin!

**Comment by NitinBhasneria** [comment]
> Ah, well, i think it's because it can't figure out how to auto-resolve them. I guess perhaps we should've done this first, but it's OK -- we can do 2 things -- try to simply rebase this over our plots2 branch, OR try to rebase the plots2 branch over this. I think without too many changes yet it's not going to be /too/ hard either way, but would you like to give one of the two a try?
> 
> Thank you, Nitin!

I think we should rebase the plots2 branch over this as we know how our changes work and so we can easily do this.
Yea, I will give a try this way.
Also, should we close this PR?

**Comment by jywarren** [comment]
Well, if you can rebase and force push here maybe that can work? Give it a
try otherwise feel free to open a new one and link from here.

Also, it's Sunday! Consider taking the day off! :-)

**Comment by NitinBhasneria** [comment]
> Well, if you can rebase and force push here maybe that can work? Give it a try otherwise feel free to open a new one and link from here. Also, it's Sunday! Consider taking the day off! :-)

I will give it a try and will update you with the same.

**Comment by NitinBhasneria** [comment]
@jywarren as this PR does not contain any of my branches, I can't edit the file changed in this PR. I have to open other PR with my branch so that I can edit and resolve the conflicts. Is it ok?

**Comment by jywarren** [comment]
Sure! Thank you!

**Pull request merged**
