### PR TITLE
Setup jest-puppeteer for UI tests

### PR DESCRIPTION
**Pull request by Shulammite-Aso**

### CODE REVIEW

**Comment by jywarren** [comment]
Wow, awesome! Perhaps you'd like to turn on Travis tests so we can see them get run in that environment? I think it could be relatively simple - like:

https://github.com/publiclab/webjack/blob/main/.travis.yml#L8

What do you think?

**Comment by Shulammite-Aso** [comment]
> Wow, awesome! Perhaps you'd like to turn on Travis tests so we can see them get run in that environment? I think it could be relatively simple - like:
> 
> https://github.com/publiclab/webjack/blob/main/.travis.yml#L8
> 
> What do you think?

Sure, will do this @jywarren 
Will also be writing the tests for bold formatting.  But having a little problem with reproducing formatting issues in a test though.☺
E.g, unlike in markdown mode where i can check whether the string **strong text** is included in text to know if it will be **bold**, i don't yet know exactly how to tell if the text you type in wysiwyg mode is Bold or not. I think using [tagName](https://developer.mozilla.org/en-US/docs/Web/API/Element/tagName) will require a class or id attribute to get the element?
I don't know if there's some obvious way i haven't thought of.

cc:@keshav234156 @emilyashley @shreyaa-s @NitinBhasneria

Other issues i think i can figure out with reading more about Jest and Puppeteer.

**Comment by Shulammite-Aso** [comment]
@jywarren please,  this repository does not already have a travis.yml file, and i thought we usually also need to add a repo to the [travis website](https://travis-ci.org/) to triger builds on the repository?

**Comment by jywarren** [comment]
Ah ok, @Shulammite-Aso i'll add it now; you should then be able to add the .travis.yml file and it'll start working!

**Comment by jywarren** [comment]
Ah ok it seems if we add it here it should work... see https://travis-ci.com/github/jywarren/woofmark

https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci-using-github

Yes, the Travis github app has access to all my repos!

**Comment by jywarren** [comment]
Thank you!

**Comment by jywarren** [comment]
And note we'll be on `.com` and not `.org` -- 🎉

**Comment by Shulammite-Aso** [comment]
> Ah ok it seems if we add it here it should work... see https://travis-ci.com/github/jywarren/woofmark
> 
> https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci-using-github
> 
> Yes, the Travis github app has access to all my repos!

Oh, great! i guess i should then add the travis.yml file and push it.

**Comment by Shulammite-Aso** [comment]
@jywarren please too, if you have any input on this https://github.com/jywarren/woofmark/pull/7#issuecomment-655086327
and this https://github.com/publiclab/PublicLab.Editor/pull/547#issuecomment-655141688 would appreciate!!

**Comment by Shulammite-Aso** [comment]
Oh! just now noticed the check here https://github.com/publiclab/PublicLab.Editor/pull/547 has completed. Finally!!!🎉

It should get merged i think?

**Comment by Shulammite-Aso** [comment]
should add a basic test to make this pass on node -v 10 and 12 at least.

**Comment by jywarren** [comment]
So, we could drop Node 8 because jest doesn't work in Node 8 -- just remove it from the `.travis.yml` and this should pass!

Great work!

**Comment by jywarren** [comment]
Awesome!!!!!

**Comment by jywarren** [comment]
This is great. Would you mind opening this against `bevacqua/woofmark` and linking here? I'm going to merge this, great work!

**Comment by jywarren** [comment]
Ah, oh wait! Actually we should have opened this against the `plots2` branch... can you open a new one and link here? Sorry about that, i should've caught it!

**Comment by jywarren** [comment]
See, most of our PRs have been against that branch: https://github.com/jywarren/woofmark/commits/plots2

Sorry about this! My bad!

**Comment by jywarren** [comment]
OK, I opened #8, check it out. Sorry again about this!

**Pull request merged**
