### PR TITLE
Bump version from 4.0.2 to 4.0.3

### PR DESCRIPTION
**Pull request by NitinBhasneria**
Bug Fix in #3 and #2.

### CODE REVIEW

**Comment by jywarren** [comment]
Oh awesome! I guess i would like to see if we could merge the in-progress Jest work from #7 first, and then write a couple simple Jest tests to demonstrate that those two bugs are resolved. What do you think?

**Comment by NitinBhasneria** [comment]
> Oh awesome! I guess i would like to see if we could merge the in-progress Jest work from #7 first, and then write a couple simple Jest tests to demonstrate that those two bugs are resolved. What do you think?

Ok, So just to be clear I have to write  the test for #3 and #2. ??

**Comment by NitinBhasneria** [comment]
Also, I am little confused about, this PR should be opened to branch `master` or branch `plots2`.
If we have to make it to master then can you please if the conflicts. Thanks.

**Comment by jywarren** [comment]
Hi, yes, this should be on `plots2` branch, which I've made the default. Sorry, just so we preserve a `master` branch from the upstream `bevacqua` fork, in case we need to do rebasing, it's good to have a copy. Cool! And, yes, please, if you could add some simple tests for #3 and #2 that would be great!

**Comment by jywarren** [comment]
Awesome! Now I need to publish this on npm. Will do soon!

**Comment by jywarren** [comment]
Oh actually we wouldn't be able to use the woofmark namespace as bevacqua already publishes this. Can you open a PR on the editor to repoint it at the GitHub address for jywarren/woofmark#plots2 using v4.0.3? I think there should be examples in there already for how to point at a GitHub url. 

Thanks! If u have trouble ping me!!

**Comment by NitinBhasneria** [comment]
Ok, will do it soon. Should we add #3 and #2 in https://github.com/publiclab/PublicLab.Editor/pull/555.

**Comment by NitinBhasneria** [comment]
@jywarren I will write the test after setting up jest test in #9

**Pull request merged**
