### PR TITLE
Update dependencies in plots2 branch

### PR DESCRIPTION
**Pull request by Shulammite-Aso**
Didn't update package.json & package-lock.json with the new dependencies for test here https://github.com/jywarren/woofmark/pull/11 this pr includes them and also included test script in `travis.yml` file and modified path to test in jest config file.

### CODE REVIEW

**Review by sagarpreet-chadha — APPROVED** [review]
Niceee :100:

**Comment by jywarren** [comment]
We can make install @dependabot here! Great work!

**Comment by jywarren** [comment]
Hi @Shulammite-Aso !! Can you try reading this since I just merged the #16 gitpod pr, to see if the not appears? Thanks!!!

**Comment by Shulammite-Aso** [comment]
> Hi @Shulammite-Aso !! Can you try reading this since I just merged the #16 gitpod pr, to see if the not appears? Thanks!!!

Okay! will rebase this.

**Comment by Shulammite-Aso** [comment]
@jywarren already rebased this.

**Comment by jywarren** [comment]
Great!!!

**Comment by jywarren** [comment]
And turning on Dependabot now!!!

**Comment by jywarren** [comment]
Just testing -- I've added @publiclab/editors as a team and invited you all! Watch out for dependabot updates on this repo now, i just turned it on 🎉 🤖

**Pull request merged**
